name: "CI/CD"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4

      - name: Install Dependencies
        run: pnpm install

      - name: "Lint"
        run: pnpm lint

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3 # Community action untuk SSH
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }} # Private key SSH
          script: |
            set -e

            APP_DIR=/root/nihongo
            REPO_URL=${{ github.server_url }}/${{ github.repository }}.git

            echo "==> Create app directory if not exists"
            mkdir -p $APP_DIR
            cd $APP_DIR

            if [ ! -d ".git" ]; then
              echo "==> Cloning repository"
              git clone $REPO_URL .
            else
              echo "==> Updating repository"
              git fetch origin
              git reset --hard origin/main
            fi

            echo "==> Create .env file"
            cat << 'EOF' > .env
            ${{ secrets.ENV_FILE }}
            EOF

            echo "==> Docker compose up"
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up --build -d
